### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by wep21** [ros2-gbp/image_transport_plugins-release#3]
@mjcarroll @clalancette @nuclearsandwich @cottsay 
Could someone create new release for rolling? The latest `ros2` branch has some bug fixes since 2.3.1.
https://github.com/ros-perception/image_transport_plugins/compare/2.3.1...ros2

**Comment by mjcarroll** [comment]
Yes, I'll get a release out for you.

**Comment by wep21** [comment]
@mjcarroll Thank you! Also, I created a backport PR which fixes the bugs above. Could someone review these changes and release them to `galactic`?
https://github.com/ros-perception/image_transport_plugins/pull/86

**Comment by mjcarroll** [comment]
Rolling: https://github.com/ros/rosdistro/pull/32250

**Comment by nuclearsandwich** [comment]
Closing since https://github.com/ros/rosdistro/pull/32250 has merged and will be in the next Rolling sync.
